POST http://localhost:3005/api/products
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RlcllvdSIsImlkIjoiNjU0Yjg3NzZjODE1ODVmM2RhMzBmZjk3Iiwicm9sZSI6InNlbGxlciIsImlhdCI6MTY5OTQ0ODg0N30.g_1HXauG83BZ4yS4mp8bFNjgkIqWJFWoCenelQpP4WI

{
    "amountAvailable": 10,
    "cost": 3.50,
    "productName": "Milk Cookies",
    "sellerId": "654b8776c81585f3da30ff97"
}